- 👋 Hi, I’m @FuseYT12
- 👀 I’m interested in Developing Bots and such engine as Python.
- 🌱 I’m currently learning 3D modeling
- 💞️ I’m looking to collaborate on Discord or many other platforms
- 📫 How to reach me: you can Follow me on Discord! 
{°Kiru°}#8686 is my user on Discord

<!---
FuseYT12/FuseYT12 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
